name: ML Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: iterative/setup-cml@v1

      - name: Setup Python Environment
        run: |
          python3 -m pip install --upgrade pip
          python3 -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt

      # Login to Weights & Biases
      - name: Login to Wandb
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          . .venv/bin/activate
          wandb login $WANDB_API_KEY

      # Login to Hugging Face
      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }} 
        run: |
          . .venv/bin/activate
          huggingface-cli login --token $HF_TOKEN

      # Run Training Script
      - name: Train
        run: |
          . .venv/bin/activate
          python main.py

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: model-artifacts
          path: |
            export/confusion_matrix.png
            checkpoints/best_model.pth

      # Generate and Post CML Report
      - name: Report Results with CML
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo '## Training Summary' >> report.md
          cat export/metric.md >> report.md
          echo '## Confusion Matrix Plot' >> report.md
          echo '![Confusion Matrix](export/confusion_matrix.png)' >> report.md
          cml comment create report.md